### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Group Actions ###
# Create Group
POST http://localhost:3000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk2ODI2NTh9.xeq7MFg-Jd-1cZVOwBT6-zOwBc-d480CPOP2JR2Z1Gs

{
  "name": "test group",
  "email": "testgroup@test.com",
  "address": "123 test st",
  "website": "www.test.com",
  "mission_statement": "we are the best at testing"
}

### Index Groups
GET http://localhost:3000/groups
Content-Type: application/json

### Update Group
PUT http://localhost:3000/groups/1
Content-Type: application/json

{
  "mission_statement": "we are really really really good at testing"
}

### Show Group
GET http://localhost:3000/groups/1
Content-Type: application/json

### Event Actions ###

### Create Event
POST http://localhost:3000/groups/1/events
Content-Type: application/json

{
  "name": "test event",
  "date": "2021/12/2",
  "start_time": "9:00",
  "duration": "90",
  "address": "123 event st.",
  "volunteers_needed": "20",
  "description": "an event where we test things"
}

### Update Event
PUT http://localhost:3000/events/2
Content-Type: application/json

{
  "name": "test event 2",
  "date": "2021/12/12"
}

### Index events
GET http://localhost:3000/events
Content-Type: application/json

### Event Show
GET http://localhost:3000/events/3
Content-Type: application/json


