### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Group Actions ###
# Create Group
POST http://localhost:3000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk5NzExMDV9.R06-a05ETE6ntYrCfaCtSdN0ZK6ntS4dWtHte95ZHhQ

{
  "name": "test group",
  "email": "testgroup@test.com",
  "address": "123 test st",
  "website": "www.test.com",
  "mission_statement": "we are the best at testing"
}

### Index Groups
GET http://localhost:3000/groups
Content-Type: application/json

### Update Group
PUT http://localhost:3000/groups/1
Content-Type: application/json

{
  "mission_statement": "we are really really really good at testing"
}

### Show Group
GET http://localhost:3000/groups/1
Content-Type: application/json

### Event Actions ###

### Create Event
POST http://localhost:3000/groups/1/events
Content-Type: application/json

{
  "name": "test event 2",
  "date": "2021/12/2",
  "start_time": "9:00",
  "duration": "90",
  "address": "123 event 2 st.",
  "volunteers_needed": "200",
  "description": "an event where we test more things"
}

### Update Event
PUT http://localhost:3000/events/2
Content-Type: application/json

{
  "name": "test event 2",
  "date": "2021/12/12"
}

### Index events
GET http://localhost:3000/events
Content-Type: application/json

### Index Groups events
GET http://localhost:3000/groups/1/events
Content-Type: application/json

### Event Show
GET http://localhost:3000/events/2
Content-Type: application/json

### RSVP actions ###

### Create rsvp
POST http://localhost:3000/events/1/rsvps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk2OTExMzF9.CNx0APMlsXCuZAAIaCy5zgfx2wgNllB_WzPOKfPUM5o

{
  "rsvp_type": "Attending"
}

### Index rsvp
GET http://localhost:3000/rsvps
Content-Type: application/json

### Show rsvp
GET http://localhost:3000/rsvps/1
Content-Type: application/json

### update rsvp
PUT http://localhost:3000/rsvps/1
Content-Type: application/json

{
  "rsvp_type": "Maybe"
}

### cause actions ###

### Create Cause
POST http://localhost:3000/causes
Content-Type: application/json

{
  "cause": "Test Cause"
}

### group_cause actions ###

### Create group_cause
POST http://localhost:3000/groups/1/causes
Content-Type: application/json

{
  "cause_id": "1"
}

### Tag actions ###

### Create new Tag
POST http://localhost:3000/tags
Content-Type: application/json

{
  "tag": "test"
}

### Event Tag actions ###

### Create new event_tag 
POST http://localhost:3000/events/2/tags
Content-Type: application/json

{
  "tag_id": "1"
}

### Index Tags
GET http://localhost:3000/tags
Content-Type: application/json


### Index Events Tags
GET http://localhost:3000/events/1/tags
Content-Type: application/json